<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MahjongSoulOverlay.Core\MahjongSoulOverlay.Core.csproj" />
    <ProjectReference Include="..\MahjongSoulOverlay.Vision\MahjongSoulOverlay.Vision.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MahjongSoulOverlay.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\MahjongSoulOverlay.Vision\Profiles\yonma-1920x1080.standard.json"
          Link="Profiles\yonma-1920x1080.standard.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
